#!/usr/bin/env python

import argparse
import sys
import logging
from smalanalysis.smali import SmaliProject, Metrics

logging.basicConfig(level=logging.INFO, format='[%(levelname)s] %(message)s', stream=sys.stderr)

parser = argparse.ArgumentParser(description='List changed methods between two APK versions.')
parser.add_argument('apk1', type=str, help='Version 1 (APK file)')
parser.add_argument('apk2', type=str, help='Version 2 (APK file)')
parser.add_argument('pkg', type=str, nargs='?', default=None, help='The app package name')
parser.add_argument('--verbose', '-v', action='store_true')
parser.add_argument('--onlyapppackage', '-P', action='store_true')
parser.add_argument('--include-unpackaged', '-U', action='store_true')
parser.add_argument('--exclude-lists', '-e', type=str, nargs='*')
parser.add_argument('--include-lists', '-i', type=str, nargs='*')
parser.add_argument('--skip-obfuscated', '-s', action='store_true')
args = parser.parse_args()

pkg = None
if args.onlyapppackage:
    pkg = args.pkg

try:
    old, _ = SmaliProject.SmaliProject.from_apk(
        args.apk1, pkg, skiplists=args.exclude_lists, includelist=args.include_lists,
        include_unpackaged=args.include_unpackaged,
    )
    if args.skip_obfuscated:
        old.removeObfuscatedClasses()

    new, _ = SmaliProject.SmaliProject.from_apk(
        args.apk2, pkg, skiplists=args.exclude_lists, includelist=args.include_lists,
        include_unpackaged=args.include_unpackaged,
    )
    if args.skip_obfuscated:
        new.removeObfuscatedClasses()

    diff = old.differences(new, [])
    for x in diff:
        if x is None or x[0] is None or x[0][0] is None:
            continue
        (sames, diffs) = x[0][0].methodsComparison(x[0][1], [])
        for fn in diffs:
            differ = fn[0] if fn[0] is not None else fn[1]
            if differ is None:
                continue
            print(differ.getFullSignature())
except Exception as e:
    print(f"Error: {e}", file=sys.stderr)
    sys.exit(1)
